# yaml-language-server: $schema=https://raw.githubusercontent.com/awslabs/goformation/master/schema/cloudformation.schema.json

AWSTemplateFormatVersion: '2010-09-09'
Description: 'Phase 1: Route53 hosted zone creation for domain nameservers'

Parameters:
  DomainName:
    Type: String
    Description: Domain name for the website
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid domain name.

Resources:
  # Route53 Hosted Zone - Create first to get nameservers
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Sub 'Hosted zone for ${DomainName}'
      Name: !Ref DomainName

Outputs:
  HostedZoneId:
    Value: !Ref HostedZone
    Description: Route53 Hosted Zone ID
    Export:
      Name: !Sub '${AWS::StackName}-HostedZoneId'
  
  NameServers:
    Value: !Join [', ', !GetAtt HostedZone.NameServers]
    Description: Name servers for the hosted zone
    Export:
      Name: !Sub '${AWS::StackName}-NameServers'