name: 🚀 Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Update version from tag
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        sed -i "s/version = \".*\"/version = \"$VERSION\"/" pyproject.toml
        sed -i "s/__version__ = \".*\"/__version__ = \"$VERSION\"/" src/awsup/__init__.py
    
    - name: Build package
      run: python -m build
    
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: twine upload dist/*